module.exports = [
  {
    artist: "50 Cent",
    genre: "Hip-Hop/ Rap",
    name: "Get Rich or Die Trying",
    year: "2003",
    songs: [
      "Intro",
      "What Up Gangsta [explicit]",
      "Patiently Waiting [feat.Eminem]",
      "Many Men (Wish Death) [explicit]",
      "In Da Club",
      "High All The Time [explicit]",
      "Heat [explicit]",
      "If I Can't [explicit]",
      "Blood Hound [feat. Young Buck]",
      "Back Down [explicit]",
      "P.I.M.P [explicit]",
      "Like My Style [feat. Tony Yayo",
      "Poor Lil Rich [explicit]",
      "21 Questions [feat. Nate Dogg]",
      "Don't Push Me [feat. Lloyd Bank]",
      "Gotta Make It To Heaven [explicit]",
      "Wanksta (from 8 Mile soundtrack)",
      "U Not Like Me [explicit]",
      "Lifes On The Line [explicit]",
      "In Da Club (A Cappella)",
    ]
  },
  {
    artist: "2 Pac",
    genre: "Hip-Hop/ Rap",
    name: "2Pac Greatest Hits (explicit version",
    year: "1998",
  },
  {
    artist: "30 Seconds To Mars",
    genre: "Alternative/ Indie",
    name: "A Beautiful Lie",
    year: "2005",
    songs: [
      "Attack",
      "A Beautiful Lie",
      "The Kill (Bury Me)",
      "Was It A Dream? [explicit]",
      "The Fantasy",
      "Savior",
      "From Yesterday [explicit]",
      "The Story",
      "R-Evolve",
      "A Modern Myth",
      "Battle of One",
      "Hunter",
      "ATTACK",
    ]
  },
  {
    artist: "A Thousand Horses",
    genre: "Country",
    name: "Broken Heartland",
    year: "2022",
  },
  {
    artist: "ABBA",
    genre: "Pop",
    name: "ABBA Gold Greatest Hits",
    year: "1992",
  },
  {
    artist: "ABC",
    genre: "Pop",
    name: "The Lexicon of Love",
    year: "1982",
  },
  {
    artist: "Aerosmith",
    name: "The Very Best of Aerosmith: Devil's Got A New Disguise",
    year: "2006",
  },
  {
    artist: "Annetha Faltskog",
    genre: "Pop",
    name: "A",
    year: "2013",
  },
  {
    artist: "Alan Jackson",
    genre: "R&B/ Soul, Jazz, Country",
    name: "Greatest Hits Volume II",
    year: "2003",
  },
  {
    artist: "Albert King",
    genre: "Blues",
    name: "The Very Best of Albert King",
    year: "2007",
  },
  {
    artist: "Alice Cooper",
    genre: "Hard Rock, Glam Rock, Heavy Metal, New Wave",
    name: "The Essential Alice Cooper - The Epic Years",
    year: "2018",
  },
  {
    artist: "Alison Krauss",
    genre: "Country",
    name: "A Hundred Miles or More: A Collection",
    year: "2007",
  },
  {
    artist: "The All American Rejects",
    genre: "Alternative/ Indies",
    name: "When The World Comes Down",
    year: "2008",
  },
  {
    artist: "Amy Winehouse",
    genre: "R&B/ Soul",
    name: "Back To Black (Deluxe Edition)[explicit]",
    year: "2006",
    songs: [
      "Rehab",
      "You Know I'm No Good",
      "Me & Mr Jones [explicit]",
      "Just Friends [explicit]",
      "Back to Black [explicit]",
      "Love Is A Losing Game",
      "Tears Dry On Their Own [explicit]",
      "Wake Up Alone",
      "Some Unholy War",
      "He Can Only Hold Her",
      "Addicted [explicit]",
      "Valerie (Live At BBC Radio 1 Live Lounge London",
      "Cupid",
      "Monkey Man",
      "Some Unholy war",
      "Hey Little Rich Girl [feat. Ade Omotayo & Zalon Thompson)",
      "You're Wondering Now",
      "To Know Him Is To Love Him (Live)",
      "Love Is a Losing Game (Original Demo)",
    ]
  },
  {
    artist: "Ariana Grande",
    genre: "Pop",
    name: "Positions [explicit]",
    year: "2020",
    songs: [
      "Shut Up",
      "34 + 35",
      "Motive [explicit]",
      "Just Like Magic [explicit]",
      "Off The Table",
      "Six Thirty [explicit]",
      "Safety Net [feat. Ty Dolla $ign]",
      "My Hair",
      "Nasty [explicit]",
      "West Side",
      "Love Language [explicit]",
      "Positions [explicit]",
      "Obvious  [explicit]",
      "POV",
    ]
  },
  {
    artist: "The Beatles",
    genre: "Psychedelic Rock, Blues",
    name: "Abbey Road (Remastered)",
    year: "1969",
  },
  {
    artist: "Bee Gees",
    genre: "Pop",
    name: "Timeless - The All-Time Greatest Hits",
    year: "2017",
  },
  {
    artist: "Belinda Carlisle",
    genre: "Pop",
    name: "Heaven On Earth",
    year: "1987",
  },
  {
    artist: "Billie Eilish",
    genre: "Pop",
    name: "Happier Than Ever [explicit]",
    year: "2021",
    songs: [
      "Getting Older",
      "I Didn't Change My Number [explicit]",
      "Billie Bossa Nova",
      "My Future",
      "Oxytocin",
      "GOLDWING",
      "Lost Cause",
      "Halley's Comet",
      "Not My Responsibility",
      "OverHeated",
      "Everybody Dies",
      "Your Power",
      "NDA [explicit]",
      "Therefore I Am",
      "Happoer Than Ever [explicit]",
      "Male Fantasy",
    ]
  },
  {
    artist: "Billie Holiday",
    genre: "Blues",
    name: "100 Hits Legends - Billie Holiday [clean]",
    year: "2010",
  },
  {
    artist: "Billy Fury",
    genre: "Metal, Pop",
    name: "A Thousand Stars: The Best Of",
    year: "2014",
  },
  {
    artist: "Blondie",
    genre: "Rock",
    name: "Against The Odds: 1974 - 1982",
    year: "2022",
  },
  {
    artist: "Boyz II Men",
    genre: "R&B/ Soul",
    name: "Legacy - The Greatest Hits Collection",
    year: "2001",
  },
  {
    artist: "Carpenters",
    genre: "Pop",
    name: "Carpenters With The Royal Philharmonic Orchestra",
    year: "2018",
    songs: [
      "Overture",
      "Yesterday Once More",
      "Hurting Each Other",
      "I Need To Be In Love",
      "For All We Know",
      "Touch Me When We're Dancing",
      "I Believe You",
      "I Just Fall In Love Again",
      "Merry Christmas, Darling,",
      "Baby It's You",
      "(They Long To Be) Close To You",
      "Superstar",
      "Ticket To Ride",
      "This Masquerade",
      "Ticket To Ride",
      "Goodbye To Love",
      "Top Of The World",
      "We've Only Just Begun",
    ]
  },
  {
    artist: "The Chemical Brothers",
    genre: "Dance/ Electronic",
    name: "No Geography",
    year: "2019",
  },
  {
    artist: "The Clash",
    genre: "Punk, Dance-Punk, New-Wave, Rock & Roll",
    name: "Hits Back",
    year: "2013",
  },
  {
    artist: "Corinne Bailey Rae",
    genre: "Pop",
    name: "The Heart Speaks In Whispers",
    year: "2016",
  },
  {
    artist: "Counting Crows",
    genre: "Rock",
    name: "Underwater Sunshine (Or What we Did on Our Summer Vacation)",
    year: "2012",
  },
  {
    artist: "The Cramps",
    genre: "Rock",
    name: "Bad Music For Bad People",
    year: "1984",
    songs: [
      "Garbage Man",
      "New Kind of Kick [explicit]",
      "Love Me",
      "I Can't Hardly Stand It",
      "She Said",
      "Goo Goo Muck",
      "Save It",
      "Human Fly",
      "Drug Train",
      "TV Set",
      "Uranium Rock",
    ]
  },
  {
    artist: "The Cranberries",
    genre: "Alternative/ Indie, Rock",
    name: "Something Else",
    year: "2017",
    songs: [
      "Linger (Acoustic Version)",
      "The Glory",
      "Dreams (Acoustic Version)",
      "When You're Gone (Acoustic Version)",
      "Zombie",
      "Ridiculous Thoughts (Acoustic Version)",
      "Rupture",
      "Ode to My Family (Acoustic Version)",
      "Free to Decide (Acoustic Version)",
      "Just My Imagination (Acoustic Version)",
      "Animal Instinct (Acoustic Version)",
      "Why",
    ],
  },
  {
    artist: "The Cure",
    genre: "Alternative/ Indie",
    name: "Greatest Hits",
    year: "2001",
  },
  {
    artist: "David Bowie",
    genre: "Rock",
    name: "Legacy (The Very Best of David Bowie) [Deluxe]",
    year: "2016",
  },
  {
    artist: "Def Leppard",
    genre: "Rock",
    name: "The Story So Far: The Best of Def Leppard",
    year: "2018",
  },
  {
    artist: "Demi Lavato",
    genre: "Pop, Pop-Rock, R&B",
    name: "Holy FVCK [explicit]",
    year: "2022",
    songs: [
      "FREAK [feat. YUNGBLUD",
      "SKIN OF MY TEETH [explicit]",
      "SUBSTANCE [explicit]",
      "EAT ME [feat. Royal & The Serpent]",
      "Holy FVCK [explicit]",
      "29 [explicit]",
      "HAPPY ENDING",
      "HEAVEN",
      "CITY OF ANGELS",
      "BONES [explicit]",
      "WASTED",
      "COME TOGETHER",
      "DEAD FRIENDS",
      "HELP ME",
      "FEED",
      "4 EVER 4 ME",
    ]
  },
  {
    artist: "Diana Ross",
    genre: "R&B, Soul",
    name: "Thank You",
    year: "2021",
  },
  {
    artist: "Drake",
    genre: "Alternative/ Indie, Hip-Hop/ Rap",
    producer_name: "40 Boi-1da",
    name: "Nothing Was The Same",
    year: "2013",
  },
  {
    artist: "Emeli Sande",
    genre: "Pop",
    name: "Let's Say For Instance",
    year: "2022",
  },
  {
    artist: "Eminem",
    genre: "Hip-Hop/ Rap, Pop",
    name: "Curtain Call 2 [explicit]",
    year: "2022",
  },
  {
    artist: "Eric B. & Rakim",
    genre: "Hip-Hop/ Rap",
    name: "Gold",
    year: "2005",
  },
  {
    artist: "Evanescence",
    genre: "Rock, Folk, Electronic Rock",
    name: "Fallen",
    year: "2003",
  },
  {
    artist: "Fleetwood Mac",
    genre: "Rock",
    name: "The Shape I'm In (Live 1972)",
    year: "2023",
    songs: [
      "Tell Me All The Things You Do",
      "Future Games",
      "Get Like You Used To Be",
      "Little Child Of Mine",
      "Spare Me A Little",
      "Homeward Bound",
      "Black Magic Woman",
      "Oh Well",
    ]
  },
  {
    artist: "Florence + The Machine",
    genre: "Alternative/ Indie",
    name: "Dance Fever",
    year: "2022",
    songs: [
      "King",
      "Free",
      "Choreomania",
      "Back In Town",
      "Girls Against God",
      "Dream Girl Evil",
      "Prayer Factory",
      "Cassandra",
      "Heaven is Here",
      "Daffodil",
      "My Love",
      "Restarint",
      "The Bomb",
      "Morning Elvis",
    ]
  },
  {
    artist: "Foo Fighters",
    genre: "Rock",
    name: "Medicine At Midnight",
    year: "2021",
    songs: [
      "Making A Fire",
      "Shame Shame",
      "Cloudspotter",
      "Waiting On A War",
      "Meicine At Midnight",
      "No Son Of Mine",
      "Holding Posion",
      "Love Dies Young",
    ]
  },
  {
    artist: "Genesis",
    genre: "Dance/ Electronic, Rock",
    name: "The Last Domino",
    year: "2021",
  },
  {
    artist: "George Michael",
    genre: "Pop",
    name: "Patience",
    year: "2004",
  },
  {
    artist: "The Go-Go's",
    genre: "Pop, Rock",
    name: "The Go-Go's - NHK FM Radio Broadcast Naka ...",
    year: "2021",
    songs: [
      "Skidmarks On My Heart",
      "How Much More",
      "Tonite",
      "Fading Fast",
      "The Way You Dance",
      "Cool Jerk",
      "Vacation",
      "You Can't Walk In Your Sleep",
      "Our Lips Are Sealed",
      "Let's Have A Party",
      "Get Up A Go",
      "We Got The Beat",
    ]
  },
  {
    artist: "Guns N' Roses",
    genre: "Rock",
    name: "Use Your Illusion I [explicit]",
    year: "2022",
    songs: [
      "Right Next Door To Hell",
      "Dust N'Bones [explicit]",
      "Live And Let Die",
      "Don't Cry",
      "Perfect Crime [explicit]",
      "You Ain't The First",
      "Bad Obsession",
      "Back Off Bitch [explicit]",
      "Double Talkin' Jive",
      "November Rain",
      "The Garden",
      "Garden Of Eden",
      "Don't Damn Me [explicit]",
      "Bad Apples",
      "Dead Horse",
      "Coma",
    ]
  },
  {
    artist: "Gwen Stefani",
    genre: "Pop",
    name: "This Is What The Truth Feels Like (delux)",
    year: "2016",
  },
  {
    artist: "Halsey",
    genre: "Pop",
    name: "Manic",
    year: "2020",
  },
  {
    artist: "Hoobastank",
    genre: "Rock",
    name: "Every Man For Himself ((Red Package))",
    year: "206",
  },
  {
    artist: "Ice Cube",
    genre: "Hip-Hop/ Rap",
    name: "Ice Cube - WTMX FM Broadcast Lollapalooz...",
    year: "2020",
  },
  {
    artist: "Imagine Dragons",
    genre: "Alternative/ Indie",
    name: "Night Visions",
    year: "2012",
  },
  {
    artist: "Iron Maiden",
    genre: "Heavy Metal",
    name: "Senjutsu",
    year: "2021",
    songs: [
      "Senjutsu",
      "Stratego",
      "The Writing On The Wall",
      "Lost In A Lost World",
      "Days Of Future Past",
      "The Time Machine",
      "Darkest Hour",
      "Death of The Celts",
      "The Parchment",
      "Hell On Earth",
    ]
  },
  {
    artist: "Jackson 5",
    genre: "R&B, Soul, Alternative/ Indie, Pop",
    name: "I Want You Back! Unreleased Masters",
    year: "2009",
  },
  {
    artist: "The Jam",
    genre: "Alternative/ Indie",
    name: "The Very Best Of The Jam",
    year: "1997",
  },
  {
    artist: "James",
    genre: "Alternative/ Indie",
    name: "Fresh As A Daisy",
    year: "2007",
  },
  {
    artist: "James Bay",
    genre: "Pop",
    name: "Chaos And The Calm",
    year: "2014",
    songs: [
      "Craving",
      "Hold Back The River",
      "Let It Go",
      "If You Ever Want To Be In Love",
      "Best Fake Smile",
      "When We Were On Fire",
      "Move Together",
      "Scars",
      "Collide",
      "Get Out While You Can",
      "Need The Sun To Break",
      "Incomplete",
    ]
  },
  {
    artist: "James Blake",
    genre: "Alternative/ Indie, Hip-Hop/ Rap",
    name: "Wind Down [James Blake & Endel]",
    year: "2022",
    songs: [
      "1st Soundscape",
      "2nd Soundscape",
      "3rd Soundscape",
      "4th Soundscape",
      "5th Soundscape",
      "6th Soundscape",
      "7th Soundscape",
      "8th Soundscape",
      "9th Soundscape",
      "10th Soundscape",
      "11th Soundscape",
      "12th Soundscape",
      "13th Soundscape",
      "14th Soundscape",
      "15th Soundscape",
    ]
  },
  {
    artist: "James Brown",
    genre: "Dance/ Electronic",
    name: "I Feel Good: The very Best Of",
    year: "2013",
  },
  {
    artist: "James Morrison",
    genre: "Pop",
    name: "You're Stronger Than You Know",
    year: "2019",
  },
  {
    artist: "Jane's Addiction",
    genre: "Alternative/ Indie",
    name: "Jane's Addiction - WTUL FM Broadcast Tipitina' ...",
    year: "2020",
  },
  {
    artist: "Janet Jackson",
    genre: "Pop",
    name: "Unbreakable",
    year: "2015",
  },
  {
    artist: "Jay-Z",
    genre: "Hip-Hop/ Rap",
    name: "4:44",
    year: "2017",
  },
  {
    artist: "Jeru The Damaja",
    genre: "Hip-Hop/ Rap",
    name: "Divine Design",
    year: "2003",
  },
  {
    artist: "Jessie J",
    genre: "Pop, Hip-Hop/ rap",
    name: "Sweet Talker",
    year: "2014",
  },
  {
    artist: "Jimi Hendrix",
    genre: "Pop, Rock",
    name: "Ten Songs For You",
    year: "2021",
    songs: [
      "All Along The Watchtower",
      "Hey Joe",
      "Voodoo Child",
      "Foxy Lady",
      "The Wind Cries Mary",
      "Somewhere",
      "Little Wing",
      "Castles Made of Sand",
      "Purple Haze",
      "Red House",
    ]
  },
  {
    artist: "Jimmy Eat World",
    genre: "Alternative/ Indie",
    name: "Surviving",
    year: "2019",
  },
  {
    artist: "Joan Armatrading",
    genre: "Rock",
    name: "Joan Armatrading - Live At Asylum Chapel",
    year: "2022",
  },
  {
    artist: "Joe Cocker",
    genre: "Rock",
    name: "Have A Little Faith In Me (edit) [single]",
    year: "2021",
  },
  {
    artist: "John Lee Hooker",
    genre: "Blues",
    name: "At Chess",
    year: "2023",
    songs: [
      "No One Told Me",
      "Big Soul",
      "I Love Her",
      "Old Time Shimmy",
      "San Francisco",
      "Take A Look At Yourself",
      "She Shot Me Down",
      "You Know I Love You",
      "Good Rockin' Mama",
      "Send Me Your Pillow",
      "Onions",
    ]
  },
  {
    artist: "Johnny Cash",
    genre: "Country",
    name: "Johnny Cash and The Philharmonic Orchestra",
    year: "2020",
  },
  {
    artist: "Johnny Gill",
    genre: "R&B/ Soul",
    name: "Game Changer",
    year: "2014",
  },
  {
    artist: "Joni Mitchell",
    genre: "Pop, Folk",
    name: "Folk Mix: Joni Mitchell & James Taylor",
    year: "2023",
  },
  {
    artist: "Joss Stone",
    genre: "R&B/ Soul, Pop, Reggae",
    name: "Never Forget My Love [explicit]",
    year: "2022",
    songs: [
      "Breaking Each Other's Hearts",
      "Never Forget My Love",
      "No Regrets",
      "Oh To Be Loved By You",
      "Love You Till The Very End",
      "You're My Girl",
      "The Greatest Secret [explicit]",
      "Does It Have To Be Today",
      "You Couldn't Kill Me [explicit]",
      "When You're In Love",
    ]
  },
  {
    artist: "Justin Bieber",
    genre: "Pop",
    name: "Justice (The Complete Edition) [explicit]",
    year: "2021",
  },
  {
    artist: "Kacey Musgraves",
    genre: "Country",
    name: "Star-Crossed",
    year: "2021",
    songs: [
      "Star-Crossed",
      "Good Wife",
      "Cherry Blossom",
      "Simple Times",
      "If This Was A Movie",
      "Justified",
      "Angel",
      "Breadwinner",
      "Camera Roll",
      "Easier Said",
      "Hookup Scene",
      "Keep Lookin' Up",
      "What Doesn't Kill Me",
      "There Is A Light",
      "Gracias a La Vida",
    ]
  },
  {
    artist: "Kaiser Chiefs",
    genre: "Alternative/ Indie, Pop",
    name: "Education, Education, Education & War",
    year: "2014",
  },
  {
    artist: "Kate Bush",
    genre: "Pop, Art Rock, Alternative/ Indie",
    name: "Selection From 'The Other Sides' (2018 Remastered)",
    year: "2018",
  },
  {
    artist: "katy Perry",
    genre: "Pop",
    name: "Smile [explicit]",
    year: "2020",
  },
  {
    artist: "Keith Urban",
    genre: "Country",
    name: "Ripcord",
    year: "2016",
  },
  {
    artist: "Kendrick Lamar",
    genre: "Hip-Hop/ Rap",
    name: "Black Panther The Album Music From And ...",
    year: "2018",
  },
  {
    artist: "The Killers",
    genre: "Alternative/ Indie",
    name: "Pressure Machine",
    year: "2022",
  },
  {
    artist: "Killing Joke",
    genre: "Rock",
    name: "PHosanna From The Basements of Hell (Deluxe)",
    year: "2022",
  },
  {
    artist: "The Kinks",
    genre: "Rock",
    name: "From Muswell Hill",
    year: "2019",
  },
  {
    artist: "Kiss",
    genre: "Hard Rock, Heavy Metal",
    name: "Creatures Of The Night (40th Anniversery/ Su ...",
    year: "2022",
  },
  {
    artist: "Lady GaGa",
    genre: "Electropop, Pop, Dance Pop",
    name: "Chromatica",
    year: "2020",
  },
  {
    artist: "Lana Del Ray",
    genre: "Indie Rock",
    name: "Norman Fucking Rockwell! [explicit]",
    year: "2019",
  },
  {
    artist: "Laura Marling",
    genre: "Alternative/ Indie",
    name: "Songs For Our Daughter",
    year: "2020",
  },
  {
    artist: "Led Zeppelin",
    genre: "Rock",
    name: "An Introduction To Led Zeppelin",
    year: "2018",
  },
  {
    artist: "The Libertines",
    genre: "Alternative/ Indie",
    name: "Up The Bracket: Early Demos",
    year: "2022",
  },
];